argparse for index column, azimuth and elevation
nens/raster-tools pull request #21
Opened 2019-04-26 07:27 UTC by wsu93

2019-04-26 07:52 UTC, arjanverkerk requested changes
Ik heb nu hier commentaar gegeven die je nu hier kunt verwerken, maar de bedoeling is dus een pull request naar de branch verkerk-py2

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +        'index_column', type=str,
Ik zou liever optionele argumenten zien, met de naam die in minor.shp zit (is dat 'name'?) als default. Zie ook het part argument hieronder. Ook voor azimuth en elevation graag optioneel maken met de defaults zoals ze hiervoor waren. 

type str is trouwens de default, mag wel maar hoeft niet.

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +        help='azimuth angle integer',
Het is toch in garden? Moet het integer zijn? Kan float niet? Wat is de definitie, cw of ccw, from north?

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +        'azimuth', type=int,
Hier ook optioneel met oorspronkelijke waarden als default.

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +        'elevation', type=int,
Hier ook. En float.

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +        help='elevation in meters integer ',
Het zijn geen meters integer, maar degrees (above horizon?).

2019-04-26 07:52 UTC, arjanverkerk commented on raster_tools/shadow.py
> +
Dit is alleen voor jou om te kunnen testen, hoeft niet in de repo.

2020-09-29 11:52 UTC, caspervdw commented
Any plans of finishing this work  @wietzesuijker  @arjanverkerk  -- feel free to close if not :)

2020-10-01 07:54 UTC, arjanverkerk commented
There seems to be little need.

2020-10-01 07:54 UTC, closed without merging